### ISSUE TITLE
MVPレビュー

### ISSUE THREAD

**Issue by Tsuchiya2** [yukari-h602/oshi-katsu#29]
MVPリリースお疲れ様でした、下記の視点をもとにレビューいたします。

1. READMEから課題解決する実装がされているか&動いている
2. 静的コードチェックが入っている
3. 就活において十分な技術力を示せる機能を実装しているか
4. UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか

## READMEから課題解決する実装がされているか&動いている
押しの布教投稿ができるのを確認しました。LGTMです。

## 静的コードチェックが入っている
インデント崩れが散見されたのでRiubocopを通しましょう。

## 就活において十分な技術力を示せる機能を実装しているか
・結論から申しますと十分な技術力は示せていないかと思いました。
・Stimulus Autocompleteによる検索機能は良いと思いましたが、それ以外はCRUDアプリという印象から脱しきれていないように思いました。
・以前のREADMEレビューで指摘した「チャット機能」の実装を行いましょう。
・いいねボタンのところは非同期処理にしましょう。
・コメント投稿時も同様に非同期処理＆スクロールしないようにしましょう。

## UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか
・ログイン前のヘッダー部分、ハンバーガーメニューが出ているのに、「ログイン」も表示されていたりと困惑しました。
・ログイン前のトップページの「押しのカルテ」の文言の箇所が左寄りになっていたりと違和感を覚えました。
・ログイン前のトップページの「押しのカルテの機能」部分も左と右でサイズが異なっており違和感を覚えました。
・押しのカルテ一覧ページも、個々の内容の多さによってマチマチになっているので統一感をもたせるように修正しましょう。
・ログイン後のヘッダー部分も横幅によって、崩れていたので修正しましょう。
・グッズ情報一覧ページのヘッダーが上部に来てしまっているせいか、白枠が大きく見えて違和感を覚えました。
・サービスにアクセスしてから、実際にサービスを触れるまでにちょっと時間がかかりすぎると感じる時があったので原因を特定して改善しておくと良いと思います。
・独自ドメインを使用しましょう。

上記のレビューをタスクに落とし込み、issueに書きましたら、こちらのissueはcloseしていただいて大丈夫です。
また書き出したissueをもとに本リリースまでのスケジュールを教えていただけますでしょうか？
よろしくお願いいたします。

**Comment by yukari-h602** [comment]
レビューありがとうございます。
いただいた内容をもとにissueを作成しました。
追加したissueはhttps://github.com/yukari-h602/oshi-katsu/issues/30 https://github.com/yukari-h602/oshi-katsu/issues/31 https://github.com/yukari-h602/oshi-katsu/issues/32 https://github.com/yukari-h602/oshi-katsu/issues/33 https://github.com/yukari-h602/oshi-katsu/issues/34 になります。
本リリースは10月中旬を予定しております。

**Comment by Tsuchiya2** [comment]
ご対応ありがとうございます。
引き続き開発頑張ってください。
